spring:
  application:
    name: nexchat-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017

    redis:
      host: localhost
      port: 6379

      # Multi-Part Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB

      # Minimum File Size
      file-size-threshold: 1KB